// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ocionejr/upvote-klever/server/common"
	"github.com/ocionejr/upvote-klever/server/repositories"
	"github.com/ocionejr/upvote-klever/server/servers"
)

// Injectors from wire.go:

func CreateServer() *common.Server {
	config := common.NewConfig()
	database := common.ConnectToDatabase(config)
	tweetRepository := repositories.NewTweetRepository(database)
	tweetServer := servers.NewTweetServer(tweetRepository)
	server := common.NewServer(config, tweetServer)
	return server
}
