// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ocionejr/upvote-klever/server/common"
	"github.com/ocionejr/upvote-klever/server/repositories"
	"github.com/ocionejr/upvote-klever/server/servers"
	"github.com/ocionejr/upvote-klever/server/services"
)

// Injectors from wire.go:

func CreateServer() *common.Server {
	config := common.NewConfig()
	database := common.ConnectToDatabase(config)
	userRepository := repositories.NewUserRepository(database)
	userService := services.NewUserService(userRepository)
	userServer := server.NewUserServer(userService)
	commonServer := common.NewServer(config, userServer)
	return commonServer
}
